import type { GenerationQuestion, QuestionSource, QuizSelections, RedisClaim } from "./types";
import { getRedisClient } from "./redis-client";

/**
 * Redis-backed question queue.
 *
 * Each question lives in a sorted set keyed by `technology:difficulty:jobTitle`
 * with `score` = epoch timestamp of when the producer enqueued it. Popping serves
 * the oldest questions first (`ZPOPMIN`); returning an unfinished assessment
 * re-adds them (`ZADD`) with their original timestamps so they're served again
 * before newer entries.
 *
 * Connects through the shared client in lib/redis-client.ts (toggle via
 * REDIS_URL env var). When Redis is not configured, the queue disables itself
 * and every quiz is generated by the model.
 */

const getClient = getRedisClient;

/** True when a Redis connection is available (configured and reachable). */
export function redisQueueEnabled(): boolean {
  return getRedisClient() !== null;
}

/** The sorted-set key for a technology/difficulty/jobTitle combination. */
export function queueKeyFor(selections: Pick<QuizSelections, "difficulty" | "jobTitle">, technology: string): string {
  return `${technology}:${selections.difficulty}:${selections.jobTitle}`;
}

export interface PoppedQuestion {
  question: GenerationQuestion;
  claim: RedisClaim;
}

/**
 * Pop up to `count` oldest questions from the queue for one key.
 * Returns the parsed questions plus their raw claims (for lossless return on
 * abandon). Throws if the queue is unreachable — callers treat that as a miss.
 */
export async function popQuestions(key: string, count: number, technology: string): Promise<PoppedQuestion[]> {
  const redis = getClient();
  if (!redis) throw new Error("Redis question queue is not configured.");

  console.log(`[redis] popping up to ${count} question(s) from "${key}"`);
  const raw = await redis.zpopmin(key, count);
  console.log(`[redis] zpopmin returned ${raw.length} raw element(s) from "${key}"`);

  // ioredis returns a FLAT array: [member, score, member, score, ...] — never
  // [[member, score], ...]. Group them back into pairs before parsing.
  const pairs: Array<[unknown, number]> = [];
  for (let i = 0; i + 1 < raw.length; i += 2) {
    pairs.push([raw[i], Number(raw[i + 1])]);
  }

  if (pairs.length === 0) {
    console.log(`[redis] key "${key}" is empty — this technology will fall back to model generation`);
    return [];
  }
  console.log(`[redis] ${pairs.length} question(s) to parse from "${key}"`);

  const popped: PoppedQuestion[] = [];
  for (const [member, score] of pairs) {
    const parsed = parseRedisMember(member);
    const question = parsed ? toGenerationQuestion(parsed, technology) : null;
    if (!question) {
      console.warn(`[redis] skipped malformed member in "${key}": ${typeof member === "string" ? member.slice(0, 200) : JSON.stringify(member).slice(0, 200)}`);
      continue;
    }
    popped.push({
      question,
      claim: { key, member: toRawMember(member), score: Number(score) },
    });
  }
  console.log(`[redis] ${popped.length} of ${pairs.length} question(s) parsed from "${key}"`);
  return popped;
}

/** Re-add previously popped questions to their queues with their original scores. */
export async function pushBackClaims(claims: RedisClaim[]): Promise<void> {
  if (claims.length === 0) return;
  const redis = getClient();
  if (!redis) throw new Error("Redis question queue is not configured.");
  const keyCount = new Set(claims.map((c) => c.key)).size;
  console.log(`[redis] returning ${claims.length} claimed question(s) to ${keyCount} key(s)`);
  const pipe = redis.pipeline();
  for (const claim of claims) {
    pipe.zadd(claim.key, claim.score, claim.member);
  }
  await pipe.exec();
}

// ---------------------------------------------------------------------------
// Member parsing / normalization
// ---------------------------------------------------------------------------

type RawMember = Record<string, unknown>;

function toRawMember(member: unknown): string {
  return typeof member === "string" ? member : JSON.stringify(member);
}

function parseRedisMember(member: unknown): RawMember | null {
  if (member && typeof member === "object" && !Array.isArray(member)) return member as RawMember;
  if (typeof member !== "string") return null;
  try {
    const parsed = JSON.parse(member) as unknown;
    return parsed && typeof parsed === "object" && !Array.isArray(parsed) ? (parsed as RawMember) : null;
  } catch {
    return null;
  }
}

function coerceSource(value: unknown): QuestionSource | undefined {
  return value === "model" || value === "official-docs" || value === "interview" ? value : undefined;
}

/**
 * Map the producer's value shape to the app's `GenerationQuestion`. The value
 * may carry extra fields (`id`, `model`, `correctAnswer`) that have no slot in
 * the app schema — `correctAnswer` is only used as a fallback when
 * `correctIndexes` is missing or malformed.
 */
function toGenerationQuestion(raw: RawMember, technology: string): GenerationQuestion | null {
  const question = String(raw.question ?? "").trim();
  if (!question) return null;

  const options = Array.isArray(raw.options) && raw.options.length === 4 ? raw.options.map((o) => String(o)) : [];
  if (!options.every((o) => o.length > 0)) return null;

  const correctIndexes =
    Array.isArray(raw.correctIndexes) && raw.correctIndexes.length >= 1
      ? raw.correctIndexes
          .map((n: unknown) => Number(n))
          .filter((n) => Number.isInteger(n) && n >= 0 && n < 4)
      : [];
  const resolvedCorrect =
    correctIndexes.length >= 1 ? [...new Set(correctIndexes)].sort((a, b) => a - b) : deriveCorrectIndexes(raw.correctAnswer, options);

  if (resolvedCorrect.length < 1) return null;

  const resolved = [...new Set(resolvedCorrect)].sort((a, b) => a - b);
  const isMultiSelect = resolved.length > 1;

  return {
    technology,
    area: String(raw.area ?? ""),
    question,
    isMultiSelect,
    options,
    correctIndexes: resolved,
    explanation: String(raw.explanation ?? ""),
    source: coerceSource(raw.source),
  };
}

// ---------------------------------------------------------------------------
// correctAnswer -> correctIndexes fallback
// ---------------------------------------------------------------------------

function normalizeText(s: string): string {
  return s.replace(/[""]/g, '"').replace(/['']/g, "'").replace(/\s+/g, " ").trim().toLowerCase();
}

function deriveCorrectIndexes(answer: unknown, options: string[]): number[] {
  const answerText = normalizeText(String(answer ?? ""));
  if (!answerText || options.length !== 4) return [];

  const normOptions = options.map((o) => normalizeText(o.replace(/^[A-Da-d]\s*[:\-]\s*/, "")));

  const singleLetter = answerText.match(/^\(?([a-d])\)?\.?$/);
  if (singleLetter) return [singleLetter[1].charCodeAt(0) - "a".charCodeAt(0)];

  // Letter-list answers ("A, B", "A and C", "(B) and (D)", "a;c") only qualify
  // when the text actually reads like a list — require a separator.
  const parts = answerText.split(/\s*[,;&]\s*|\s+and\s+/).map((p) => p.trim()).filter((p) => p.length > 0);
  if (parts.length >= 2) {
    const multi = new Set<number>();
    for (const part of parts) {
      const letter = part.replace(/[()]/g, "").match(/^([a-d])\.?$/);
      if (letter) {
        multi.add(letter[1].charCodeAt(0) - "a".charCodeAt(0));
      } else {
        const match = deriveCorrectIndexes(part, options);
        if (match.length === 1) multi.add(match[0]);
      }
    }
    if (multi.size >= 2) return [...multi].sort((a, b) => a - b);
  }

  for (let i = 0; i < normOptions.length; i++) {
    if (normOptions[i] === answerText) return [i];
  }

  for (let i = 0; i < normOptions.length; i++) {
    if (answerText.includes(normOptions[i]) || normOptions[i].includes(answerText)) return [i];
  }

  const answerWords = new Set(answerText.split(/\s+/));
  let best = -1;
  let bestRatio = 0;
  for (let i = 0; i < normOptions.length; i++) {
    const optWords = new Set(normOptions[i].split(/\s+/));
    const shared = [...answerWords].filter((w) => optWords.has(w)).length;
    const ratio = shared / answerWords.size;
    if (ratio > bestRatio) {
      bestRatio = ratio;
      best = i;
    }
  }
  return bestRatio >= 0.7 ? [best] : [];
}
